version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: spark_mongodb
    ports:
      - 27017:27017
    environment:      
      - MONGO_INITDB_ROOT_USERNAME=spark
      - MONGO_INITDB_ROOT_PASSWORD=spark
    networks:
      - spark-network

    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: spark_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=spark
      - POSTGRES_USER=spark
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: spark_elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node     
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - script.painless.regex.enabled=true
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: spark_kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart: unless-stopped

  pubsub-emulator:
    image: google/cloud-sdk
    container_name: spark_pubsub_emulator
    ports:
      - 8085:8085
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
    restart: unless-stopped

volumes:
  mongodb_data:
  postgres_data:
  elasticsearch_data:

networks:
  spark-network:
    driver: bridge